### PR TITLE
Add ability to perform partial user updates

### PR DESCRIPTION
**Pull request by briguy202**
This pull is to expose the API's ability to submit partial user updates via POST calls, as instructed in the [Okta Documentation](http://developer.okta.com/docs/api/resources/users.html):

> Use the POST method to make a partial update and the PUT method to delete unspecified properties.

### CODE REVIEW

**Comment by briguy202** [comment]
Also, while considering this pull, could I also propose that the version in the POM have the 'SNAPSHOT' removed?

**Comment by jpf** [comment]
Hi @briguy202 - thanks for this PR, I also note that PR #34 also requested similar changes. I've opened an internal ticket (OKTA-106322) for the team that manages this SDK.

Out of curiosity, I'm wondering:
- Are you using the methods that you added in production code?
- What is the use case that you needed to solve with this update?

**Comment by briguy202** [comment]
Hi @jpf, in response to your questions:
* Yes, we are using the methods in production code.
* The use case we had was updating logins without needing to touch any other properties on the user's profile.

**Comment by jmelberg-okta** [comment]
This enhancement looks to have been added in a [recent update (#47)](https://github.com/okta/oktasdk-java/pull/47/).

**Pull request closed without merging**
