### PR TITLE
:bug: Service-side changes break getting AppInstance

### PR DESCRIPTION
**Pull request by AlainODea**
Problem: JSON for Vpn under Notifications changed on service side and
was no longer possible to read AppInstance objects back.

Solution: make offending data classes extend ApiObject.

Alternative Solution (not included): accept JSON with unknown
properties in **JsonApiClient**:

**src/main/java/com/okta/sdk/framework/JsonApiClient.java**:

```java
objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
```

### CODE REVIEW

**Comment by AlainODea** [comment]
A service-side change recently went into Okta production that makes it impossible to get AppInstances with the Java SDK (oktasdk-java).

Here is a minimal example to reproduce the bug:

```java
import com.okta.sdk.clients.AppInstanceApiClient;
import com.okta.sdk.framework.ApiClientConfiguration;
import com.okta.sdk.models.apps.AppInstance;

import java.io.IOException;

public class Main {
    public static void main(String[] args) throws IOException {
        ApiClientConfiguration config = new ApiClientConfiguration(
                "https://verafin.okta.com/", "00N8_stMAI5lYP-bVZZA5je6T8di-bDiXZa9TAFNzg"
        );
        AppInstanceApiClient appInstanceApiClient = new AppInstanceApiClient(config);
        AppInstance appInstance = appInstanceApiClient.getAppInstance("0oa1a5epbdcQ9WfKi1t7");
        System.out.println(appInstance);
    }
}
```

Here is the output:

```plain
Exception in thread "main" com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "helpUrl" (class com.okta.sdk.models.apps.Notifications$Vpn), not marked as ignorable (2 known properties: "network", "message"])
 at [Source: org.apache.http.client.entity.LazyDecompressingInputStream@cad498c; line: 1, column: 659] (through reference chain: com.okta.sdk.models.apps.AppInstance["settings"]->com.okta.sdk.models.apps.Settings["notifications"]->com.okta.sdk.models.apps.Notifications["vpn"]->com.okta.sdk.models.apps.Vpn["helpUrl"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:817)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:954)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1315)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:249)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3532)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1892)
	at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:1434)
	at com.okta.sdk.framework.JsonApiClient.unmarshall(JsonApiClient.java:69)
	at com.okta.sdk.framework.ApiClient.unmarshallResponse(ApiClient.java:305)
	at com.okta.sdk.framework.ApiClient.get(ApiClient.java:173)
	at com.okta.sdk.clients.AppInstanceApiClient.getAppInstance(AppInstanceApiClient.java:104)
	at Main.main(Main.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by peggyxue-okta** [comment]
I reproduce this issue at my local with our in-house environment oktapreview.com, logged an JIRA **OKTA-114777** for this exception

**Comment by jmelberg-okta** [comment]
@AlainODea : Great find. When updating our models, it looks like we didn't include the `helpUrl` in our `Notifications.java` class. I've pushed an update that will fix this issue.

Thanks for your contributions!

**Comment by AlainODea** [comment]
@jmelberg-okta good stuff. I've rebased this change on master to make it easier to integrate.

I think it makes sense to have **Notifications.Vpn** and **Notifications.Vpn.Network** extend **ApiObject**. Right now they are the only model classes that don't extend **ApiObject**. It would protect the Java SDK deployments in the field from future additions to the service-side JSON.

**Comment by AlainODea** [comment]
@jmelberg-okta this broke in production for us. What is the plan for handling future service-side JSON changes? If Vpn or Network change again on the service-side it will break the oktasdk-java again and we'll have to scramble again which is a bad customer experience.

**Comment by jmelberg-okta** [comment]
@AlainODea: Yikes. I'll be working with the team to implement these changes as soon as possible.

We are in the process of implementing a new SDK test suite. This should minimize future errors due to changes service-side.

Thank you for letting us know!

**Pull request merged**
